version: '3.8'

services:
  agent_pro:
    build: ./agent_pro
    ports:
      - "5001:5000"  # IP 제거, 포트만 매핑
    volumes:
      - ./models:/app/models:ro
    env_file:
      - .env  
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - SERVICE_NAME=agent_pro
    networks:
      debate_network:
        aliases:
          - agent_pro
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 16G
        reservations:
          cpus: '0.5'
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  agent_con:
    build: ./agent_con
    ports:
      - "5002:5000"
    volumes:
      - ./models:/app/models:ro
    env_file:
      - .env
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - SERVICE_NAME=agent_con
    networks:
      debate_network:
        aliases:
          - agent_con
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 16G
        reservations:
          cpus: '0.5'
          memory: 8G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mediator:
    build: ./mediator
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models:ro
    env_file:
      - .env
    environment:
      - MODEL_PATH=${MODEL_PATH}
      - SERVICE_NAME=mediator
      - AGENT_PRO_URL=http://agent_pro:5000  # 로컬호스트 or 서버 주소
      - AGENT_CON_URL=http://agent_con:5000
    networks:
      debate_network:
        aliases:
          - mediator
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 16G
        reservations:
          cpus: '0.5'
          memory: 8G
    depends_on:
      agent_pro:
        condition: service_healthy
      agent_con:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  debate_network:
    driver: bridge
